name: Continuous Deployment

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install Serverless Framework
        run: bun add -g serverless

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure Serverless Framework
        run: |
          mkdir -p ~/.serverless
          echo '{"accessKey": "${{ secrets.SERVERLESS_ACCESS_KEY }}", "org": "${{ secrets.SERVERLESS_ORG }}"}' > ~/.serverless/credentials.json
          export SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }}
          export SERVERLESS_ORG=${{ secrets.SERVERLESS_ORG }}
          serverless login --org ${{ secrets.SERVERLESS_ORG }}

      - name: Get Production Secrets
        if: github.ref == 'refs/heads/main'
        run: |
          aws secretsmanager get-secret-value --secret-id prod/nestjs-base-api --query SecretString --output text > .env
          echo "NODE_ENV=production" >> .env

      - name: Get Development Secrets
        if: github.ref == 'refs/heads/develop'
        run: |
          aws secretsmanager get-secret-value --secret-id dev/nestjs-base-api --query SecretString --output text > .env
          echo "NODE_ENV=development" >> .env

      - name: Build Application
        run: bun run build

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          SERVERLESS_ORG: ${{ secrets.SERVERLESS_ORG }}
        run: bun run deploy:prod

      - name: Deploy to Development
        if: github.ref == 'refs/heads/develop'
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          SERVERLESS_ORG: ${{ secrets.SERVERLESS_ORG }}
        run: bun run deploy:dev
